ktor:
    application:
        modules:
            - com.intch.ApplicationKt.module
    deployment:
        port: 8080
    development: true
jwt:
    domain: "https://jwt-provider-domain/"
    audience: "jwt-audience"
    realm: "ktor sample app"

storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://db:5432/intouch?user=postgres"